<a href="https://colab.research.google.com/github/Manasa-Sairi/NNDL_ICP3/blob/main/NNDL_ICP3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:

#Employee Class
class Employee:
    num_of_employees = 0

    #initializing the attributes
    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.num_of_employees += 1

    #Average Salary Method
    def averageSalary(self, employees):
        total_salary = sum(emp.salary for emp in employees)
        return total_salary / len(employees)
#Full Time Employee Class - Super Class
class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department, employment_type):
        super().__init__(name, family, salary, department)
        self.employment_type = employment_type

# Instances of Employee class
employee1 = Employee("Nivas", "Sairi", 50000, "Senior Software")
employee2 = Employee("Manasa", "Sairi", 80000, "Manager")

# Instances of FulltimeEmployee class
fulltime1 = FulltimeEmployee("Afreen", "Begum", 50000, "Engineering", "FullTime")
fulltime2 = FulltimeEmployee("Mallika", "venam", 60000, "Marketing", "PartTime")

# Call member functions
employees = [employee1, employee2, fulltime1, fulltime2]
avgSalary = employee1.averageSalary(employees)

print("Total Employees:", Employee.num_of_employees)
print("Average Salary:", avgSalary)


Total Employees: 4
Average Salary: 60000.0


In [1]:
import numpy as np
#generating a vector
vector = np.random.uniform(1, 20, 20)

#reshaping the vector into 4 * 5 matrix
matrix = vector.reshape(4, 5)

print("Original Matrix: \n",matrix)

#finding the index of the max element along axis = 1
indices = np.argmax(matrix, axis=1)

#Create a range of indices for each row
row_indices = np.arange(matrix.shape[0])

#Use advanced indexing to replace max values with 0
matrix[row_indices, indices] = 0

print("Resultant Matrix: \n",matrix)


Original Matrix: 
 [[ 8.32931813  4.37128747  3.59617478  8.25034931 13.89372329]
 [13.26715621 19.14978532 18.59458404  3.74493385 12.83775549]
 [ 7.07944109 11.24343097 14.06950517  2.11341656 17.35466612]
 [ 2.45963082 18.8228951   9.24280584 17.71295382  4.00512132]]
Resultant Matrix: 
 [[ 8.32931813  4.37128747  3.59617478  8.25034931  0.        ]
 [13.26715621  0.         18.59458404  3.74493385 12.83775549]
 [ 7.07944109 11.24343097 14.06950517  2.11341656  0.        ]
 [ 2.45963082  0.          9.24280584 17.71295382  4.00512132]]
